name: deploy envinronment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev or staging'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set default enevironment
        run: echo "echo $GITHUB_EVENT_NAME"

      - name: set default enevironment
        run: echo "DEPLOYMENT_ENV=dev" >> $GITHUB_ENV

      - name: in a case of main branch
        run: echo "DEPLOYMENT_ENV=staging" >> $GITHUB_ENV
        if:  github.ref == 'ref/head/main'

      - name: read terraform_version
        id: terraform_version
        uses: juliangruber/read-file-action@v1
        with:
          path: .terraform-version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.content }}

      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.inputs.environemnt || env.DEPLOYMENT_ENV }}

      - name: make deploy
        run: make

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
