name: deploy envinronment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev or staging'
        required: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
  TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: pip install invoke python-dotenv ansible==2.9.2 requests

      - name: read terraform_version
        id: terraform_version
        uses: juliangruber/read-file-action@v1
        with:
          path: .terraform-version

      - name: set default enevironment
        run: echo "DEPLOYMENT_ENV=$(inv which-environment | tail -n1)" >> $GITHUB_ENV

      - name: print ansible version
        run: echo "ansible-playbook --version"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_wrapper: false
          terraform_version: ${{ steps.terraform_version.outputs.content }}

      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ env.DEPLOYMENT_ENV }}

      - name: run invoke
        run: invoke all
        env:
          DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}

      - run: cat inventory.yml
        env:
          DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}


      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
