on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch submodule_push event
        uses: mvasigh/dispatch-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: kharandziuk
          event_type: deploy-environment
          message: |
            {
                "environment": "staging"
            }
