name: destroy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev or staging'
        required: true

jobs:
  destroy-environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: pip install invoke python-dotenv ansible==2.9.2 requests

      - name: read terraform_version
        id: terraform_version
        uses: juliangruber/read-file-action@v1
        with:
          path: .terraform-version

      - name: set default enevironment
        run: echo "DEPLOYMENT_ENV=$(inv which-environment | tail -n1)" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.content }}

      - name: make destroy
        run: make terraform-destroy

      - name: run invoke
        run: invoke destroy-infrastructure
        env:
          DEPLOYMENT_ENV: ${{ env.DEPLOYMENT_ENV }}

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.inputs.environment }}
