name: destroy infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'dev or staging'
        required: true

jobs:
  destroy-environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: read terraform_version
        id: terraform_version
        uses: juliangruber/read-file-action@v1
        with:
          path: .terraform-version

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ steps.terraform_version.outputs.content }}

      - name: make destroy
        run: make terraform-destroy

      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        with:
          step: deactivate-env
          token: ${{ secrets.GITHUB_TOKEN }}
          env: ${{ github.event.inputs.environment }}
