name: destroy infrastructure everyday

on:
  schedule: # schedule action every five minutes
      # * is a special character in YAML so you have to quote this string
    - cron:  '*/0 1 * * *'

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: destroy infrastructure
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{ "environment": "dev"}'

      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: destroy infrastructure
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          inputs: '{ "environment": "staging"}'


